import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    name: "Red Wine",
    slug: "red-wine",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80",
    description: "Explore our curated selection of red wines from renowned vineyards worldwide.",
    subcategories: [
      { name: "Cabernet Sauvignon", slug: "cabernet-sauvignon" },
      { name: "Malbec", slug: "malbec" },
      { name: "Merlot", slug: "merlot" },
      { name: "Pinot Noir", slug: "pinot-noir" },
      { name: "Zinfandel", slug: "zinfandel" },
    ],
  },
  {
    name: "White Wine",
    slug: "white-wine",
    image: "https://images.unsplash.com/photo-1543489822-c49534f3271f?w=600&q=80",
    description: "Crisp and refreshing white wines perfect for any occasion.",
    subcategories: [
      { name: "Chardonnay", slug: "chardonnay" },
      { name: "Pinot Grigio", slug: "pinot-grigio" },
      { name: "Riesling", slug: "riesling" },
      { name: "Sauvignon Blanc", slug: "sauvignon-blanc" },
    ],
  },
  {
    name: "Champagne",
    slug: "champagne",
    image: "https://images.unsplash.com/photo-1594372365401-3b5ff14eaaed?w=600&q=80",
    description: "Celebrate with our finest champagnes and sparkling wines.",
  },
  {
    name: "Whiskey",
    slug: "whiskey",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&q=80",
    description: "From smooth bourbon to peaty scotch, discover exceptional whiskeys.",
    subcategories: [
      { name: "Bourbon", slug: "bourbon" },
      { name: "Scotch", slug: "scotch" },
      { name: "Irish Whiskey", slug: "irish-whiskey" },
      { name: "Japanese Whiskey", slug: "japanese-whiskey" },
      { name: "Rye Whiskey", slug: "rye-whiskey" },
    ],
  },
  {
    name: "Tequila",
    slug: "tequila",
    image: "https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=600&q=80",
    description: "Premium tequilas and mezcals from Mexico's finest distilleries.",
  },
  {
    name: "Vodka",
    slug: "vodka",
    image: "https://images.unsplash.com/photo-1607622750671-6cd9a99eabd1?w=600&q=80",
    description: "Crystal clear vodkas from around the world.",
  },
  {
    name: "Rum",
    slug: "rum",
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&q=80",
    description: "Caribbean and craft rums for every palate.",
  },
  {
    name: "Gin",
    slug: "gin",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80",
    description: "Botanical gins from classic London Dry to modern craft.",
  },
  {
    name: "Cognac & Brandy",
    slug: "cognac-brandy",
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&q=80",
    description: "Fine cognacs and brandies for the discerning connoisseur.",
  },
  {
    name: "Beer",
    slug: "beer",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80",
    description: "Craft and classic beers from around the world.",
  },
];

export const products: Product[] = [
  // RED WINE
  {
    id: "rw-001",
    name: "Caymus Napa Valley Cabernet Sauvignon",
    slug: "caymus-napa-valley-cabernet-sauvignon",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=500&q=80",
    category: "red-wine",
    subcategory: "cabernet-sauvignon",
    description: "A rich, full-bodied Cabernet Sauvignon from one of Napa Valley's most iconic wineries. Dark fruit flavors with hints of cocoa and vanilla from oak aging.",
    volume: "750ml",
    abv: "14.6%",
    region: "Napa Valley, California",
    rating: 4.8,
    inStock: true,
    featured: true,
    badge: "Best Seller",
  },
  {
    id: "rw-002",
    name: "Jordan Alexander Valley Cabernet Sauvignon",
    slug: "jordan-alexander-valley-cabernet",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&q=80",
    category: "red-wine",
    subcategory: "cabernet-sauvignon",
    description: "Elegant and balanced with flavors of blackberry, cassis, and a touch of spice. A classic Sonoma County expression.",
    volume: "750ml",
    abv: "13.7%",
    region: "Alexander Valley, California",
    rating: 4.6,
    inStock: true,
    featured: true,
  },
  {
    id: "rw-003",
    name: "Malbec Reserve Mendoza",
    slug: "malbec-reserve-mendoza",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=500&q=80",
    category: "red-wine",
    subcategory: "malbec",
    description: "Deep purple with aromas of plum, blackberry and violet. Smooth tannins with a long finish.",
    volume: "750ml",
    abv: "14.5%",
    region: "Mendoza, Argentina",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "rw-004",
    name: "Decoy California Pinot Noir",
    slug: "decoy-california-pinot-noir",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=500&q=80",
    category: "red-wine",
    subcategory: "pinot-noir",
    description: "Light and aromatic with flavors of cherry, strawberry and subtle earthy notes. Silky texture.",
    volume: "750ml",
    abv: "13.9%",
    region: "Sonoma County, California",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "rw-005",
    name: "Silver Oak Alexander Valley Cabernet",
    slug: "silver-oak-alexander-valley-cabernet",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=500&q=80",
    category: "red-wine",
    subcategory: "cabernet-sauvignon",
    description: "Lush and full-bodied with layers of dark cherry, blackberry and baking spice. American oak aging.",
    volume: "750ml",
    abv: "13.9%",
    region: "Alexander Valley, California",
    rating: 4.7,
    inStock: true,
    featured: true,
    badge: "Premium",
  },
  {
    id: "rw-006",
    name: "Bread & Butter Cabernet Sauvignon",
    slug: "bread-butter-cabernet-sauvignon",
    price: 14.99,
    compareAtPrice: 18.99,
    image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=500&q=80",
    category: "red-wine",
    subcategory: "cabernet-sauvignon",
    description: "Smooth and approachable with ripe berry flavors and a hint of toasted oak.",
    volume: "750ml",
    abv: "13.5%",
    region: "California",
    rating: 4.1,
    inStock: true,
    badge: "Sale",
  },

  // WHITE WINE
  {
    id: "ww-001",
    name: "Santa Margherita Pinot Grigio",
    slug: "santa-margherita-pinot-grigio",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=500&q=80",
    category: "white-wine",
    subcategory: "pinot-grigio",
    description: "Dry, crisp and elegant with notes of golden apple and citrus. Italy's most famous Pinot Grigio.",
    volume: "750ml",
    abv: "12.5%",
    region: "Trentino-Alto Adige, Italy",
    rating: 4.5,
    inStock: true,
    featured: true,
  },
  {
    id: "ww-002",
    name: "Cloudy Bay Sauvignon Blanc",
    slug: "cloudy-bay-sauvignon-blanc",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1562601579-599dec564e06?w=500&q=80",
    category: "white-wine",
    subcategory: "sauvignon-blanc",
    description: "Vibrant and aromatic with passion fruit, citrus and fresh herb notes. Iconic New Zealand expression.",
    volume: "750ml",
    abv: "13.5%",
    region: "Marlborough, New Zealand",
    rating: 4.6,
    inStock: true,
    featured: true,
  },
  {
    id: "ww-003",
    name: "Kendall-Jackson Chardonnay",
    slug: "kendall-jackson-chardonnay",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=500&q=80",
    category: "white-wine",
    subcategory: "chardonnay",
    description: "Rich and buttery with tropical fruit flavors, vanilla and a creamy texture.",
    volume: "750ml",
    abv: "13.5%",
    region: "California",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "ww-004",
    name: "Dr. Loosen Riesling",
    slug: "dr-loosen-riesling",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=500&q=80",
    category: "white-wine",
    subcategory: "riesling",
    description: "Off-dry with bright acidity, green apple, peach and mineral notes. A German classic.",
    volume: "750ml",
    abv: "8.5%",
    region: "Mosel, Germany",
    rating: 4.4,
    inStock: true,
  },

  // CHAMPAGNE
  {
    id: "ch-001",
    name: "Veuve Clicquot Yellow Label Brut",
    slug: "veuve-clicquot-yellow-label-brut",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1594372365401-3b5ff14eaaed?w=500&q=80",
    category: "champagne",
    description: "The iconic yellow label. Fresh and forceful with a rich, toasty complexity and fine bubbles.",
    volume: "750ml",
    abv: "12%",
    region: "Champagne, France",
    rating: 4.7,
    inStock: true,
    featured: true,
    badge: "Popular",
  },
  {
    id: "ch-002",
    name: "Moët & Chandon Impérial Brut",
    slug: "moet-chandon-imperial-brut",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=500&q=80",
    category: "champagne",
    description: "Bright fruit intensity with white-fleshed fruits and citrus. Elegant and generous.",
    volume: "750ml",
    abv: "12%",
    region: "Champagne, France",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "ch-003",
    name: "Dom Pérignon Vintage",
    slug: "dom-perignon-vintage",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=500&q=80",
    category: "champagne",
    description: "The quintessential prestige cuvée. Complex layers of almond, cocoa and bright citrus. Extraordinary finesse.",
    volume: "750ml",
    abv: "12.5%",
    region: "Champagne, France",
    rating: 4.9,
    inStock: true,
    badge: "Luxury",
  },

  // WHISKEY
  {
    id: "wh-001",
    name: "Maker's Mark Bourbon",
    slug: "makers-mark-bourbon",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&q=80",
    category: "whiskey",
    subcategory: "bourbon",
    description: "Handmade small batch bourbon with a smooth, approachable flavor. Caramel, vanilla and fruit notes.",
    volume: "750ml",
    abv: "45%",
    region: "Kentucky, USA",
    rating: 4.4,
    inStock: true,
    featured: true,
  },
  {
    id: "wh-002",
    name: "Macallan 12 Year Double Cask",
    slug: "macallan-12-year-double-cask",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&q=80",
    category: "whiskey",
    subcategory: "scotch",
    description: "Matured in a combination of sherry and American oak casks. Rich and creamy with honey, citrus and ginger.",
    volume: "750ml",
    abv: "43%",
    region: "Speyside, Scotland",
    rating: 4.7,
    inStock: true,
    featured: true,
    badge: "Top Rated",
  },
  {
    id: "wh-003",
    name: "Jameson Irish Whiskey",
    slug: "jameson-irish-whiskey",
    price: 26.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "whiskey",
    subcategory: "irish-whiskey",
    description: "Triple distilled for exceptional smoothness. Light floral fragrance with spicy, sweet notes.",
    volume: "750ml",
    abv: "40%",
    region: "Cork, Ireland",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "wh-004",
    name: "Hibiki Japanese Harmony",
    slug: "hibiki-japanese-harmony",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&q=80",
    category: "whiskey",
    subcategory: "japanese-whiskey",
    description: "A harmonious blend of malt and grain whiskeys. Subtle rose, lychee and a hint of rosemary.",
    volume: "750ml",
    abv: "43%",
    region: "Japan",
    rating: 4.8,
    inStock: true,
    badge: "Premium",
  },
  {
    id: "wh-005",
    name: "Bulleit Rye Whiskey",
    slug: "bulleit-rye-whiskey",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1609951651556-5334e2706168?w=500&q=80",
    category: "whiskey",
    subcategory: "rye-whiskey",
    description: "Spicy character with notes of cherry, vanilla and just a hint of smokiness. Bold and balanced.",
    volume: "750ml",
    abv: "45%",
    region: "Kentucky, USA",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "wh-006",
    name: "Woodford Reserve Bourbon",
    slug: "woodford-reserve-bourbon",
    price: 38.99,
    image: "https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=500&q=80",
    category: "whiskey",
    subcategory: "bourbon",
    description: "Complex and balanced with rich dried fruit, vanilla, and toasted oak notes. Triple pot distilled.",
    volume: "750ml",
    abv: "45.2%",
    region: "Kentucky, USA",
    rating: 4.6,
    inStock: true,
  },

  // TEQUILA
  {
    id: "tq-001",
    name: "Patrón Silver Tequila",
    slug: "patron-silver-tequila",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=500&q=80",
    category: "tequila",
    description: "Crystal clear with fresh agave aromas, citrus and light pepper notes. Ultra-smooth finish.",
    volume: "750ml",
    abv: "40%",
    region: "Jalisco, Mexico",
    rating: 4.5,
    inStock: true,
    featured: true,
  },
  {
    id: "tq-002",
    name: "Don Julio 1942 Añejo",
    slug: "don-julio-1942-anejo",
    price: 169.99,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&q=80",
    category: "tequila",
    description: "Rich caramel, chocolate and roasted agave flavors. Aged minimum 2.5 years in American white oak.",
    volume: "750ml",
    abv: "40%",
    region: "Jalisco, Mexico",
    rating: 4.9,
    inStock: true,
    badge: "Luxury",
  },
  {
    id: "tq-003",
    name: "Clase Azul Reposado",
    slug: "clase-azul-reposado",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "tequila",
    description: "Aged 8 months in American whiskey casks. Smooth with vanilla, caramel and spice notes.",
    volume: "750ml",
    abv: "40%",
    region: "Jalisco, Mexico",
    rating: 4.8,
    inStock: true,
    badge: "Premium",
  },

  // VODKA
  {
    id: "vd-001",
    name: "Grey Goose Original Vodka",
    slug: "grey-goose-original-vodka",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1607622750671-6cd9a99eabd1?w=500&q=80",
    category: "vodka",
    description: "Made from fine French wheat and spring water. Smooth with gentle sweetness and white pepper notes.",
    volume: "750ml",
    abv: "40%",
    region: "Picardy, France",
    rating: 4.4,
    inStock: true,
    featured: true,
  },
  {
    id: "vd-002",
    name: "Belvedere Pure Vodka",
    slug: "belvedere-pure-vodka",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "vodka",
    description: "Four times distilled Polish rye vodka. Creamy with vanilla and white pepper finish.",
    volume: "750ml",
    abv: "40%",
    region: "Poland",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "vd-003",
    name: "Tito's Handmade Vodka",
    slug: "titos-handmade-vodka",
    price: 22.99,
    compareAtPrice: 27.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "vodka",
    description: "Crafted from yellow corn in old-fashioned pot stills. Gluten-free and incredibly smooth.",
    volume: "750ml",
    abv: "40%",
    region: "Austin, Texas",
    rating: 4.3,
    inStock: true,
    badge: "Sale",
  },

  // RUM
  {
    id: "rm-001",
    name: "Diplomático Reserva Exclusiva",
    slug: "diplomatico-reserva-exclusiva",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&q=80",
    category: "rum",
    description: "Rich and complex with toffee, brown sugar and dried fruit notes. Aged up to 12 years.",
    volume: "750ml",
    abv: "40%",
    region: "Venezuela",
    rating: 4.7,
    inStock: true,
    featured: true,
  },
  {
    id: "rm-002",
    name: "Bacardi Superior White Rum",
    slug: "bacardi-superior-white-rum",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "rum",
    description: "Light and aromatically balanced. Perfect for cocktails with subtle almond and lime notes.",
    volume: "750ml",
    abv: "40%",
    region: "Puerto Rico",
    rating: 3.9,
    inStock: true,
  },

  // GIN
  {
    id: "gn-001",
    name: "Hendrick's Gin",
    slug: "hendricks-gin",
    price: 36.99,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&q=80",
    category: "gin",
    description: "Infused with cucumber and rose petals for a delightfully unique flavor. Smooth with floral notes.",
    volume: "750ml",
    abv: "44%",
    region: "Scotland",
    rating: 4.6,
    inStock: true,
    featured: true,
  },
  {
    id: "gn-002",
    name: "Tanqueray London Dry Gin",
    slug: "tanqueray-london-dry-gin",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "gin",
    description: "A perfectly balanced gin with four distinct botanicals. Crisp and refreshing juniper-led profile.",
    volume: "750ml",
    abv: "47.3%",
    region: "England",
    rating: 4.4,
    inStock: true,
  },

  // COGNAC & BRANDY
  {
    id: "cb-001",
    name: "Hennessy VS Cognac",
    slug: "hennessy-vs-cognac",
    price: 42.99,
    image: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&q=80",
    category: "cognac-brandy",
    description: "Bold and fragrant with lively notes of toasted almond, fresh grapes, and a touch of cinnamon.",
    volume: "750ml",
    abv: "40%",
    region: "Cognac, France",
    rating: 4.4,
    inStock: true,
    featured: true,
  },
  {
    id: "cb-002",
    name: "Rémy Martin VSOP",
    slug: "remy-martin-vsop",
    price: 54.99,
    image: "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&q=80",
    category: "cognac-brandy",
    description: "Mellow and harmonious with vanilla, stone fruit and licorice notes. Exceptionally well-rounded.",
    volume: "750ml",
    abv: "40%",
    region: "Cognac, France",
    rating: 4.6,
    inStock: true,
  },
  // BEER
  {
    id: "beer-001",
    name: "Corona Extra Lager",
    slug: "corona-extra-lager",
    price: 1.00,
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=500&q=80",
    category: "beer",
    description: "A refreshing, crisp pilsner-style lager with a smooth taste. Best served ice cold with a wedge of lime.",
    volume: "355ml",
    abv: "4.6%",
    region: "Mexico",
    rating: 4.2,
    inStock: true,
    featured: true,
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category === categorySlug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  );
}
